services:
  backend:
    build: ../backend
    volumes:
      - ../backend:/app
    expose:
      - "8000"
    env_file:
      - ../.env

  frontend:
    image: node:20-alpine
    container_name: react_frontend
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5186"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5186:5186"
    depends_on:
      - backend
