services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./frontend-angular/app/public/nacional:/app/frontend-public/nacional:ro
      - ./frontend-angular/app/public/fichas:/app/frontend-public/fichas:ro
      - ./frontend-angular/app/public/oficios:/app/frontend-public/oficios
      - type: bind
        source: C:/Users/david.baltazar/OneDrive - imssmx/Archivos de Rohan Myron Oprisko - Fotos de Unidades Médicas  (File responses)
        target: /app/ficha/assets/fotos_origen
        read_only: true
      - type: bind
        source: C:/Users/david.baltazar/OneDrive - imssmx/Archivos de Rohan Myron Oprisko - Fotos de FACHADASUnidades Médicas  (File responses)
        target: /app/ficha/assets/fotos_fachada
        read_only: true
    expose:
      - "8100"
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx_proxy1
    ports:
      - "8088:80"
    depends_on:
      - backend
    volumes:
      - ./frontend-angular/app/public/fichas:/usr/share/nginx/html/fichas:ro
      - ./frontend-angular/app/public/nacional:/usr/share/nginx/html/nacional:ro
      - ./frontend-angular/app/public/oficios:/usr/share/nginx/html/oficios:ro
      - ./backend/ficha/output_fichas:/app/ficha/output_fichas
