apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: marioahvelazquez-dev
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  DJANGO_LOG_LEVEL: "INFO"
---
apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: marioahvelazquez-dev
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-change-this-in-production"
  DB_NAME: "your_database_name"
  DB_USER: "your_db_user"
  DB_PASS: "your_db_password"
  DB_HOST: "your_db_host"
