apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: backend
  namespace: marioahvelazquez-dev
spec:
  lookupPolicy:
    local: false
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: frontend
  namespace: marioahvelazquez-dev
spec:
  lookupPolicy:
    local: false
