apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: frontend-service
    weight: 100
  wildcardPolicy: None
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: backend
  labels:
    app: backend
spec:
  path: /api
  port:
    targetPort: 8000-tcp
  to:
    kind: Service
    name: backend-service
    weight: 100
  wildcardPolicy: None
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
